#!/usr/bin/env bash

if ! pipenv run python -m flake8; then
    echo 'Fichier mal formaté'
    pipenv run python -m black *.py
    exit 1
fi

if ! pipenv run python -m pytest *test.py; then
    echo 'Tests en erreur'
    exit 1
fi
